### ISSUE TITLE
idiff needs to compare (1) before, (2) after, and (3) reference images.

### ISSUE THREAD

**Issue by HalCanary** [mtklein/idiff#1]
idiff needs to compare (1) before, (2) after, and (3) reference images.

**Comment by mtklein** [comment]
I don't really know that it needs to, but it sounds fine to me if you want to add it.
Please make it optional:
  $ idiff before after [reference] [diff.html]

You might consider also running idiff twice.

**Comment by mtklein** [comment]
If you're looking to do other fancy things (diff stats, sorting, etc) that's all fine too, provided it stays roughly as fast as it is now.  I don't mind that requires the code to become x86-specific (or even x86-64 specific) but I would like it to run on Mac, Linux, and Windows.
